"""Order refactor ENUM -> look-up table

Revision ID: af34f2484c7f
Revises: 61cc5e83cfa7
Create Date: 2025-11-22 17:41:26.604546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af34f2484c7f'
down_revision: Union[str, Sequence[str], None] = '61cc5e83cfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('order_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.add_column('order_items', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'order_item_statuses', ['status_id'], ['id'])
    op.drop_column('order_items', 'status')
    op.add_column('orders', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'order_statuses', ['status_id'], ['id'])
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', postgresql.ENUM('pending', 'served', 'paid', 'cancelled', name='orderstatus'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'status_id')
    op.add_column('order_items', sa.Column('status', postgresql.ENUM('pending', 'cooking', 'served', 'cancelled', name='orderitemstatus'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'status_id')
    op.drop_table('order_statuses')
    op.drop_table('order_item_statuses')
    # ### end Alembic commands ###
