"""Resource: refactor ingredient, equipment ENUM -> look-up table

Revision ID: d3d107188257
Revises: 1c6fc8eb2fd3
Create Date: 2025-11-22 17:33:58.262567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3d107188257'
down_revision: Union[str, Sequence[str], None] = '1c6fc8eb2fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('equipment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredient_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('equipments', sa.Column('type_id', sa.Integer(), nullable=False))
    op.add_column('equipments', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'equipments', 'equipment_statuses', ['status_id'], ['id'])
    op.create_foreign_key(None, 'equipments', 'equipment_types', ['type_id'], ['id'])
    op.drop_column('equipments', 'status')
    op.drop_column('equipments', 'type')
    op.add_column('ingredients', sa.Column('unit_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ingredients', 'ingredient_units', ['unit_id'], ['id'])
    op.drop_column('ingredients', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('unit', postgresql.ENUM('grams', 'kilograms', 'liters', 'pieces', name='unit'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'unit_id')
    op.add_column('equipments', sa.Column('type', postgresql.ENUM('pending', 'oven', 'stove', 'grill', 'fridge', 'freezer', 'microwave', 'sink', 'dishwasher', 'coffee_machine', name='equipmenttype'), autoincrement=False, nullable=False))
    op.add_column('equipments', sa.Column('status', postgresql.ENUM('available', 'in_use', 'maintenance', 'broken', name='equipmentstatus'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'equipments', type_='foreignkey')
    op.drop_constraint(None, 'equipments', type_='foreignkey')
    op.drop_column('equipments', 'status_id')
    op.drop_column('equipments', 'type_id')
    op.drop_table('ingredient_units')
    op.drop_table('equipment_types')
    op.drop_table('equipment_statuses')
    # ### end Alembic commands ###
