"""payment refactoring

Revision ID: f0238d8018db
Revises: 1d8b06ca6e47
Create Date: 2025-11-22 17:12:09.523448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0238d8018db'
down_revision: Union[str, Sequence[str], None] = '1d8b06ca6e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.add_column('payments', sa.Column('booking_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('payments', sa.Column('method_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('provider_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('provider_transaction_id', sa.String(length=255), nullable=False))
    op.add_column('payments', sa.Column('status_id', sa.Integer(), nullable=False))
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.create_unique_constraint(None, 'payments', ['provider_transaction_id'])
    op.drop_constraint(op.f('payments_order_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'payment_providers', ['provider_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'payment_statuses', ['status_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'orders', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'payment_methods', ['method_id'], ['id'])
    op.drop_column('payments', 'method')
    op.drop_column('payments', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('method', postgresql.ENUM('cash', 'mobile', 'card', name='paymentmethod'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_order_id_fkey'), 'payments', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'payments', type_='unique')
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('payments', 'status_id')
    op.drop_column('payments', 'provider_transaction_id')
    op.drop_column('payments', 'provider_id')
    op.drop_column('payments', 'method_id')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'booking_id')
    op.drop_table('payment_statuses')
    op.drop_table('payment_providers')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
