"""minor fix

Revision ID: 1d8b06ca6e47
Revises: ee8975574d50
Create Date: 2025-11-17 18:08:59.815266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8b06ca6e47'
down_revision: Union[str, Sequence[str], None] = 'ee8975574d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('quantity', sa.Float(), nullable=True))
    op.drop_column('ingredients', 'qunatity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('qunatity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('ingredients', 'quantity')
    # ### end Alembic commands ###
