"""add guest and link to order

Revision ID: 40f6573b3c7a
Revises: af34f2484c7f
Create Date: 2025-11-22 19:42:44.197990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f6573b3c7a'
down_revision: Union[str, Sequence[str], None] = 'af34f2484c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cointact_info', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('guest_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'guests', ['guest_id'], ['id'])
    op.add_column('users', sa.Column('contact_info', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['contact_info'])
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'name')
    op.drop_column('users', 'contact_info')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'guest_id')
    op.drop_table('guests')
    # ### end Alembic commands ###
