"""add email for user

Revision ID: 501a3e6d1f9c
Revises: d41b4524cac4
Create Date: 2025-12-11 00:41:01.116284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501a3e6d1f9c'
down_revision: Union[str, Sequence[str], None] = 'd41b4524cac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('gateway_txn_ref', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('payments', 'expired_at')
    op.drop_column('payments', 'gateway_txn_ref')
    # ### end Alembic commands ###
