"""ingre hist

Revision ID: 5ce5db6b9b73
Revises: 04c1a438dd9f
Create Date: 2025-12-10 21:04:29.651639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce5db6b9b73'
down_revision: Union[str, Sequence[str], None] = '04c1a438dd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_histories', sa.Column('old_quantity', sa.Float(), nullable=False))
    op.add_column('ingredient_histories', sa.Column('new_quantity', sa.Float(), nullable=False))
    op.add_column('ingredient_histories', sa.Column('quantity_change', sa.Float(), nullable=False))
    op.drop_column('ingredient_histories', 'change')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_histories', sa.Column('change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('ingredient_histories', 'quantity_change')
    op.drop_column('ingredient_histories', 'new_quantity')
    op.drop_column('ingredient_histories', 'old_quantity')
    # ### end Alembic commands ###
