"""sample equipment type added

Revision ID: ee8975574d50
Revises: fcf51f337425
Create Date: 2025-11-16 17:32:51.017067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ee8975574d50'
down_revision: Union[str, Sequence[str], None] = 'fcf51f337425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    #manual
    equipment_enum = postgresql.ENUM(
        'pending',
        'oven',
        'stove',
        'grill',
        'fridge',
        'freezer',
        'microwave',
        'sink',
        'dishwasher',
        'coffee_machine',
        name='equipmenttype'
    )
    equipment_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    'equipments',
    'type',
    type_=sa.Enum(
        'pending', 'oven', 'stove', 'grill', 'fridge', 
        'freezer', 'microwave', 'sink', 'dishwasher', 'coffee_machine', 
        name='equipmenttype'
    ),
    existing_type=sa.VARCHAR(length=50),
    postgresql_using="type::equipmenttype",
    existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipments', 'type',
               existing_type=sa.Enum('pending', 'oven', 'stove', 'grill', 'fridge', 'freezer', 'microwave', 'sink', 'dishwasher', 'coffee_machine', name='equipmenttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
